- name: Obtener valores os_family, hostname e ipv4
  hosts: all
  become: yes
  tasks:
    - name: Obtener valor os_family
      debug:
        msg: "El sistema operativo de mi m치quina es {{ ansible_os_family }}"

    - name: Obtener valor hostname
      debug:
        msg: "El nombre de mi m치quina es {{ ansible_hostname }}"

    - name: Obtener valor ipv4
      debug:
        msg: "La direcci칩n IP de mi m치quina es {{ ansible_default_ipv4.address }}"