---
- name: Instalar paquetes 
  hosts: webserver
  tasks:
    - name: Obtener información del sistema
      setup:

    - name: Instalar paquetes en Ubuntu
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - openssh-server
        - python3
      when: ansible_distribution == 'Ubuntu'
      tags:
        - ubuntu

    - name: Instalar paquetes en CentOS
      command: yum install -y {{ item }}
      loop:
        - openssh-server
        - python3
      when: ansible_distribution in ['CentOS', 'Fedora', 'RedHat']
      tags:
        - centos
...
---
- name: Instalar paquetes según la distribución del host
  hosts: webserver
  tasks:
    - name: Obtener información del sistema
      setup:

    - name: Instalar paquetes centos fedora y redhat
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - openssh-server
        - python3
      when: ansible_distribution in ['CentOS', 'Fedora', 'RedHat']

    - name: Instalar paquetes en Ubuntu
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - openssh-server
        - python3
      when: ansible_distribution == 'Ubuntu'

... 